---
resources:
- name: learning
  type: git
  source: {uri: "https://github.com/0xRand0m/concourse-learning.git"}

jobs:
- name: hello-job
  plan:
    - get: learning
      trigger: true
    - task: generate-output
      input_mapping:
        learning-git: learning
      output_mapping:
        output: generated-output
      params:
        NAME: Jan
      file: learning/jobs/generate-message.yml
    - task: print-output
      input_mapping:
        learning-git: learning
        message: generated-output
      file: learning/jobs/hello-world.yml
