---
resources:
- name: repo-dev-test
  type: git
  source:
    uri: {uri: "https://github.com/0xRand0m/concourse-learning.git"}
    branch: dev-test

jobs:
- name: check-if-file-exists
  plan:
    - get: repo-dev-test
      trigger: true
    - task: check-if-file-exists-task # task name
      #file: repo-dev-test/jobs/check-if-file-exists-task.yaml
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: alpine
            tag: '3.15'
        run:
          #path: repo-dev-test/jobs/check-if-file-exists.sh
          path: echo
          args: ["Hello Task"]
