---
resources:
- name: repo-dev-test
  type: git
  source:
    uri: https://github.com/0xRand0m/concourse-learning.git
    branch: dev-test

jobs:
  - name: check-if-file-exists
    plan:
      - get: repo-dev-test
        trigger: true
      - task: check-if-file-exists-task # task name
        #file: repo-dev-test/jobs/check-if-file-exists-task.yaml
        #config:
        file: repo-dev-test/jobs/check-if-file-exists-task.yml
        input_mapping:
          repo-path: repo-dev-test
        output_mapping:
          output: generated-output
        params:
          NAME: repo-dev-test/README.md
          FILE: repo-dev-test/README.md
      - task: print-output
        input_mapping:
          repo-path: repo-dev-test
          output: generated-output
        file: epo-dev-test/jobs/return-if-file-exists-task.yml
