---
resources:
- name: learning
  type: git
  source: {uri: "https://github.com/0xRand0m/concourse-learning.git"}

jobs:
- name: Hello World
  plan:
  - get: learning
    trigger: true
  - task: Hello World
    input-mappings:
      learning-git: learning
    params:
      NAME: Jan
    file: learning/jobs/hello-world.yml
