---
resources:
- name: repo-dev-test
  type: git
  source:
    uri: https://github.com/0xRand0m/concourse-learning.git
    branch: dev-test

jobs:
  #- get: repo-dev-test
  #  trigger: true
  - name: check-if-file-exists
    plan:
      - get: repo-dev-test
        trigger: true
      - task: check-if-file-exists-task # task name
        #file: repo-dev-test/jobs/check-if-file-exists-task.yaml
        #config:
        file: repo-dev-test/jobs/check-if-file-exists-task.yaml
        input_mapping:
          learning-git: learning
        output_mapping:
          output: generated-output
        params:
          file: repo-dev-test/README.md
